// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbhwg49K4s18KgSt1d_5QZ2re8H6l95j4',
    appId: '1:183024653774:web:a6eaa25b376240709e879f',
    messagingSenderId: '183024653774',
    projectId: 'fruit-hub-72972',
    authDomain: 'fruit-hub-72972.firebaseapp.com',
    storageBucket: 'fruit-hub-72972.firebasestorage.app',
    measurementId: 'G-YL5N4EWL6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvtVjo1YnWdrtgX0XoHqlcIsKBwe7r-P0',
    appId: '1:183024653774:android:b85b9a8f28f054469e879f',
    messagingSenderId: '183024653774',
    projectId: 'fruit-hub-72972',
    storageBucket: 'fruit-hub-72972.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiMTE2TCMmxMFhL01VRBgynRYVmVlqAI8',
    appId: '1:183024653774:ios:bce0e55370b648389e879f',
    messagingSenderId: '183024653774',
    projectId: 'fruit-hub-72972',
    storageBucket: 'fruit-hub-72972.firebasestorage.app',
    androidClientId: '183024653774-g0gupmrvp3g8brnkvtdi9bm5v8g3gtsg.apps.googleusercontent.com',
    iosClientId: '183024653774-n4irduagfsp9d5vm03onkm75bn806ilg.apps.googleusercontent.com',
    iosBundleId: 'com.example.justmartDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiMTE2TCMmxMFhL01VRBgynRYVmVlqAI8',
    appId: '1:183024653774:ios:bce0e55370b648389e879f',
    messagingSenderId: '183024653774',
    projectId: 'fruit-hub-72972',
    storageBucket: 'fruit-hub-72972.firebasestorage.app',
    androidClientId: '183024653774-g0gupmrvp3g8brnkvtdi9bm5v8g3gtsg.apps.googleusercontent.com',
    iosClientId: '183024653774-n4irduagfsp9d5vm03onkm75bn806ilg.apps.googleusercontent.com',
    iosBundleId: 'com.example.justmartDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLQRQOooyPHCYMHsIVeaPYpTNl--C5Ii4',
    appId: '1:183024653774:web:9ee4d6eb593871b09e879f',
    messagingSenderId: '183024653774',
    projectId: 'fruit-hub-72972',
    authDomain: 'fruit-hub-72972.firebaseapp.com',
    storageBucket: 'fruit-hub-72972.firebasestorage.app',
    measurementId: 'G-VDX1BMDJXZ',
  );
}
